import prisma from "@/lib/prisma";
import {
  getAdminNotificationEmail,
  getMailTransporter,
} from "@/lib/mailConfig";

export async function POST(request) {
  const { name, email, phone, subject, message } = await request.json();

  let transporter;
  let fromEmail;
  let notifyEmail;

  try {
    ({ transporter, fromEmail } = getMailTransporter());
    notifyEmail = await getAdminNotificationEmail();
  } catch (error) {
    console.error("Contact mail config:", error);
    return Response.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }

  const adminMailOptions = {
    from: `Ocean Lifespaces Contact Form <${fromEmail}>`,
    to: notifyEmail,
    subject: `New Contact Form Submission: ${subject}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">New Contact Request</h1>
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone}</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <p><strong>Message:</strong></p>
          <p>${message.replace(/\n/g, "<br>")}</p>
        </div>
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>This email was automatically generated by the Ocean Lifespaces contact form.</p>
        </div>
      </div>
    `,
  };

  const userMailOptions = {
    from: `Ocean Lifespaces <${fromEmail}>`,
    to: email,
    subject: "Thank You for Contacting Ocean Lifespaces",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">Thank You for Contacting Us!</h1>
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>We've received your message and will get back to you soon.</p>
          <p>Here's what you submitted:</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <p><strong>Message:</strong></p>
          <p>${message.replace(/\n/g, "<br>")}</p>
        </div>
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>© ${new Date().getFullYear()} Ocean Lifespaces. All rights reserved.</p>
        </div>
      </div>
    `,
  };

  try {
    await prisma.enquiry.create({
      data: {
        type: "Contact",
        name,
        email,
        mobile: phone,
        subject,
        message,
        status: "new",
      },
    });

    await transporter.verify();
    await transporter.sendMail(adminMailOptions);
    await transporter.sendMail(userMailOptions);

    return Response.json({ success: true });
  } catch (error) {
    console.error("Contact send error:", error);
    return Response.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
