export const ARCHITECT_PARTNERS = [
  "Adrianse India Pvt Ltd",
  "Architecture Red",
  "Arvind Varuna",
  "Aswathanarayana & Eswara",
  "Atelier Global",
  "C R Narayana Rao",
  "C S Designs Pvt Ltd",
  "Charles Correa",
  "Decon Architects",
  "Design Studio",
  "Design Transit",
  "Dsp Architects",
  "Dwp Interiors",
  "Edifice Consultants Pvt Ltd",
  "Gensler",
  "HBO + EMTB, Singapore",
  "KGD Architects",
  "M+W Group",
  "Madras Designs",
  "M-Cube Architects",
  "Mmoser Associates",
  "Praxis Inc",
  "PSP Architects",
  "PTK Architects",
  "Quadra Architects Pvt Ltd",
  "RAJ Consultants",
  "Rapidcorp Architects",
  "RSP Architects",
  "Sankalpan",
  "Sara Interiors",
  "Space Matrix",
  "Sudhakar Pai Associates",
  "Swbi",
  "Symmetrix",
  "TATA Consulting Engineers",
  "Varsha & Pradeep",
  "Vijay Punjabi",
];

export const PMC_PARTNERS = [
  "AN Prakash",
  "Builtech",
  "CBRE",
  "Colliers International",
  "Cushman & Wakefield",
  "FABS",
  "Faithful + Gould",
  "Integrate PMC India Pvt Ltd",
  "JLL",
  "Potential Project Managers Pvt Ltd",
  "Promat",
  "SSJ PICIPL",
  "Synergy",
  "Turner & Townsend",
];
